export const USER_REACTIVE_SOURCE_CHANGED = 'USER_REACTIVE_SOURCE_CHANGED'
export const USER_LOGGING_REACTIVE_SOURCE_CHANGED = 'USER_LOGGING_REACTIVE_SOURCE_CHANGED'
export const USER_INITIALIZATION_START = 'USER_INITIALIZATION_START'
